image: ruby:2.5.5

services:
  - postgres:9.6

variables:
  RUNNING_ON_CI_SERVER: 1
  POSTGRES_DB: reely_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - /cache

before_script:

  # Add Google Chrome's repo to sources list
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list

  # Install Google's public key used for signing packages (e.g. Chrome)
  # (Source: http://www.google.com/linuxrepositories/)
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

  # System
  - apt-get update -qq

  # Google Chrome
  - apt-get -y -qq install libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4
  - apt-get -y -qq install google-chrome-stable
  - which google-chrome
  - google-chrome --version

  # Chromedriver (2.42)
  # All versions can be found here: http://chromedriver.storage.googleapis.com/
  - apt-get install unzip
  - wget -N http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip -P /tmp
  - unzip /tmp/chromedriver_linux64.zip -d /tmp
  - chmod +x /tmp/chromedriver
  - mv -f /tmp/chromedriver /usr/local/share/chromedriver
  - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  - which chromedriver
  - chromedriver --version

  # Dependencies to make "headless" chrome/selenium work:
  - apt-get -y -qq install xvfb gtk2-engines-pixbuf
  - apt-get -y -qq install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable

  # NodeJS (JavaScript runtime)
  - apt-get -y -qq install nodejs

  # Xvfb
  - apt-get install -y -qq xvfb

  # Ruby
  - ruby -v
  - which ruby

  # Required specifically for json v1.8.3
  # See: https://stackoverflow.com/a/35384604/10252006
  - apt-get install -y -qq libgmp3-dev

  # Ruby Gems
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler
  - bundle install --path=/cache --without production --jobs $(nproc) "${FLAGS[@]}"

  # App
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate

rspec:
  script:
    # See: https://github.com/thoughtbot/capybara-webkit#ci
    - xvfb-run -a bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
